[[post]]
category = "Cloud Computing"
title = "AWS Certified Cloud Practitioner"
#subtitle = ""
datetime = "2024-10-23"
image = "config/assets/posts/aws-certified-cloud-practitioner.png"
url = "https://www.credly.com/badges/837b42cd-d7c4-4818-b82f-4c740c16a6a6/public_url"

[[post]]
category = "Python Programming"
title = "Pieran Data Complete Python Bootcamp"
#subtitle = ""
datetime = "2022-10-27"
image = "config/assets/posts/udemy.png"
url = "https://drive.google.com/file/d/18JUk-ZNrLQgMU_LXNCdugsCYgU1hi7K-/view"

[[post]]
category = "Data Analytics"
title = "Google Data Analytics Professional Certificate"
#subtitle = ""
datetime = "2023-03-05"
image = "config/assets/posts/Coursera.png"
url = "https://drive.google.com/drive/folders/1wmpmPGGlZbw8J1MBTtVMloAnTq3iG3oA?usp=sharing"

[[post]]
category = "Data Analytics"
title = "Quantium Data Analytics Job Simulation"
#subtitle = ""
datetime = "2024-03-13"
image = "config/assets/posts/Quantium.jpg"
url = "https://drive.google.com/file/d/1gsDHlKttesVfXNqPRYIGfk-WWCcxsed7/view"

[[post]]
category = "SQL"
title = "Pieran Data Complete SQL Bootcamp"
#subtitle = ""
datetime = "2024-06-15"
image = "config/assets/posts/udemy.png"
url = "https://drive.google.com/file/d/10cw-yO6HbRQ_KO4l0dDxKZ0DMlHRKg3y/view"

#[[post]]
#category = "Design"
#title = "UI interactions of the week"
#subtitle = "Enim ad minim veniam, consectetur adipiscing elit, quis nostrud exercitation ullamco laboris nisi"
#datetime = "2022-02-23"
#image = "./config/assets/posts/blog-4.jpg"
#url = "https://dev.to"

#[[post]]
#category = "Design"
#title = "The Forgotten Art Of Spacing"
#subtitle = "Maxime placeat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"
#datetime = "2022-02-23"
#image = "./config/assets/posts/blog-5.jpg"
#url = "https://medium.com"

#[[post]]
#category = "Design"
#title = "Design Digest #79"
#subtitle = "Optio cumque nihil impedit uo minus quod maxime placeat, velit esse cillum"
#datetime = "2022-02-23"
#image = "./config/assets/posts/blog-6.jpg"
#url = "https://hashnode.com"
